Repository akuity/kargo-render, pull requests merged in 2023-10, with the labels that each got.

#185 rename project to Kargo Render
  .github/governance.yml
  .github/workflows/release.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  action.yaml
  branches.go
  branches_test.go
  cmd/action/action.go
  cmd/action/logger.go
  cmd/action/request.go
  cmd/action/request_test.go
  cmd/cli/render_cmd.go
  cmd/cli/root_cmd.go
  cmd/cli/version_cmd.go
  cmd/main.go
  config.go
  config_test.go
  context.go
  docs/docs/10-overview.md
  docs/docs/20-environment-branches.md
  docs/docs/30-how-to-guides/10-configuration.mdx
  docs/docs/30-how-to-guides/20-github-actions.md
  docs/docs/30-how-to-guides/30-docker-image.md
  docs/docs/30-how-to-guides/40-go-module.md
  docs/docs/40-contributor-guide/10-hacking-on-kargo-render.md
  docs/docs/40-contributor-guide/20-signing-commits.md
  docs/docs/40-contributor-guide/index.md
  docs/docs/50-roadmap.md
  docs/docusaurus.config.js
  go.mod
  internal/github/pr.go
  internal/helm/config.go
  internal/helm/helm.go
  internal/kustomize/config.go
  internal/kustomize/kustomize.go
  internal/log/logger.go
  internal/ytt/config.go
  internal/ytt/ytt.go
  logging.go
  pkg/git/git.go
  prs.go
  rendering.go
  rendering_test.go
  schema.json
  service.go
  service_test.go
  types.go
  validation.go
  validation_test.go
Labels: kind/refactor, priority/high

#191 remove gh action definition
  action.yaml
Labels: kind/chore, priority/normal

#198 Add kargo logo and a link to the kargo discord server
  README.md
  kargo-logo.png
  logo.png
Labels: area/documentation, kind/refactor, priority/normal

#207 add netlify.toml
  netlify.toml
Labels: kind/chore, priority/normal

#206 suppress logging from repo server
  cmd/cli/cli.go
Labels: priority/high

#208 clean commit branches more thoroughly
  branches.go
  branches_test.go
Labels: kind/refactor, priority/high

#209 send all log output to stderr
  cmd/cli/cli.go
Labels: kind/chore, kind/refactor, priority/high

#212 add config option to exempt specific paths from pre-render branch cleaning
  branches.go
  branches_test.go
  config.go
  schema.json
Labels: kind/enhancement, priority/high
