Repository akuity/kargo-render, pull requests merged in 2023-09, with the labels that each got.

#168 return error instead of panicking upon branch hijacking
  service.go
Labels: kind/bug, priority/normal

#170 docs & action def: pre-release version bump
  action.yaml
  docs/docs/30-how-to-guides/20-github-actions.md
  docs/docs/30-how-to-guides/30-docker-image.md
Labels: area/documentation, kind/chore, priority/normal

#175 chore: bump Kustomize to 5.1.1
  Dockerfile
  action.yaml
Labels: kind/chore, priority/normal, dependencies

#177 Update CODEOWNERS
  CODEOWNERS
Labels: kind/chore, priority/normal

#173 Support setting helm namespace in Bookfile
  docs/docs/30-how-to-guides/10-configuration.mdx
  internal/helm/config.go
  internal/helm/helm.go
  rendering.go
  rendering_test.go
  schema.json
  service.go
Labels: kind/enhancement, priority/normal
