Repository akuity/kargo-render, pull requests merged in 2024-03, with the labels that each got.

#250 Ensure Helm can write files in container image
  Dockerfile
Labels: kind/bug

#261 feat: add options for where input comes from and where output goes to
  .github/workflows/ci.yaml
  Dockerfile
  branches.go
  cmd/action_cmd.go
  cmd/action_cmd_test.go
  cmd/flags.go
  cmd/root_cmd.go
  context.go
  docs/docs/30-how-to-guides/30-docker-image.md
  go.mod
  go.sum
  pkg/git/git.go
  pkg/git/git_test.go
  service.go
  types.go
  validation.go
  validation_test.go
Labels: kind/enhancement, priority/high

#266 improve how new branches are created
  branches.go
  docs/docs/30-how-to-guides/30-docker-image.md
  pkg/git/git.go
  service.go
Labels: kind/refactor, priority/high

#268 fix: preserve files correctly when rendering to a local directory
  branches.go
  branches_test.go
  config_test.go
  docs/docs/30-how-to-guides/30-docker-image.md
  pkg/git/git.go
  rendering.go
  service.go
  service_test.go
Labels: kind/bug, priority/high

#272 remove unnecessary push when rendering to local path
  branches.go
  docs/docs/30-how-to-guides/30-docker-image.md
  pkg/git/git.go
  pkg/git/git_test.go
Labels: kind/bug, priority/high
